import { spawnSync } from 'node:child_process'
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const REGISTRY_DIR = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const OUT_DIR = resolve(REGISTRY_DIR, 'dist/r')

const run = (command, args) => {
  const result = spawnSync(command, args, {
    cwd: REGISTRY_DIR,
    stdio: 'inherit',
    shell: process.platform === 'win32',
  })
  if (result.status !== 0) {
    process.exit(result.status ?? 1)
  }
}

// 1. Build the registry catalog with the shadcn CLI. `-c` pins the working
//    directory (this package) and `-o` puts the flattened catalog + per-item
//    JSON wherever we like — the deploy worker serves them from here.
run('pnpm', ['dlx', 'shadcn@latest', 'build', '-c', REGISTRY_DIR, '-o', OUT_DIR])

// 2. Generate a worker index over the built item JSONs so the deploy worker
//    can serve /r/{name}.json without knowing the item list ahead of time.
const itemFiles = readdirSync(OUT_DIR)
  .filter((file) => file.endsWith('.json') && file !== 'registry.json')
  .sort()

const identifierFor = (file) => `_${file.slice(0, -'.json'.length).replace(/[^a-zA-Z0-9]/g, '_')}`

const importLines = itemFiles.map((file) => `import ${identifierFor(file)} from './${file}'`)
const itemEntries = itemFiles.map(
  (file) => `  ${JSON.stringify(file.slice(0, -'.json'.length))}: ${identifierFor(file)},`,
)

mkdirSync(OUT_DIR, { recursive: true })

writeFileSync(
  resolve(OUT_DIR, 'worker-index.mjs'),
  `// Generated by packages/registry/scripts/build.mjs — do not edit.
import _registry from './registry.json'
${importLines.join('\n')}

export const catalog = _registry

export const items = {
  registry: _registry,
${itemEntries.join('\n')}
}
`,
)

writeFileSync(
  resolve(OUT_DIR, 'worker-index.d.mts'),
  `// Generated by packages/registry/scripts/build.mjs — do not edit.
export declare const catalog: unknown
export declare const items: Record<string, unknown>
`,
)

const catalog = JSON.parse(readFileSync(resolve(OUT_DIR, 'registry.json'), 'utf8'))
console.log(`registry build complete: ${itemFiles.length + 1} items → ${OUT_DIR}`)
console.log(`catalog: ${catalog.name} — homepage ${catalog.homepage}`)
